# Generated by Django 5.0.6 on 2024-06-05 15:57

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detailed_descr', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique_for_date='time_created')),
                ('in_progress', models.BooleanField(choices=[('PROG', 'In progress'), ('IDLE', 'Idle')], default='PROG')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('time_to_finish', models.DateTimeField(blank=True, null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('performers', models.ManyToManyField(related_name='tasks', related_query_name='task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_created'],
                'indexes': [models.Index(fields=['slug', 'time_created'], name='tasks_task_slug_d7fc38_idx')],
            },
        ),
    ]
