# Generated by Django 5.0.6 on 2024-06-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='in_progress',
            field=models.CharField(choices=[('PROG', 'In progress'), ('IDLE', 'Idle')], default='PROG', max_length=4),
        ),
    ]
